services:
  # --------------------------
  # S3 хранилище (MinIO)
  # --------------------------
  minio:
    image: minio/minio:latest
    container_name: geo-minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - geo-net

  # --------------------------
  # ClickHouse (аналитическая БД)
  # --------------------------
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: geo-clickhouse
    ports:
      - "8123:8123"
      - "9009:9009"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ../clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ../clickhouse/config/users.xml:/etc/clickhouse-server/users.d/custom-users.xml:ro
    networks:
      - geo-net

  # --------------------------
  # Postgres (метаданные Airflow)
  # --------------------------
  postgres:
    image: postgres:13
    container_name: geo-airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geo-net

  # --------------------------
  # Airflow DB migration (init)
  # --------------------------
  airflow-init:
    image: apache/airflow:2.8.1
    container_name: geo-airflow-init
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate &&
      airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests"
    networks:
      - geo-net

  # --------------------------
  # Airflow Webserver
  # --------------------------
  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: geo-airflow-webserver
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests"
    ports:
      - "8080:8080"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    command: webserver
    networks:
      - geo-net

  # --------------------------
  # Airflow Scheduler
  # --------------------------
  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: geo-airflow-scheduler
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      PIP_ADDITIONAL_REQUIREMENTS: "boto3 requests"
    volumes:
      - ../airflow/dags:/opt/airflow/dags
      - ../airflow/logs:/opt/airflow/logs
      - ../airflow/plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - geo-net

  # --------------------------
  # Grafana
  # --------------------------
  grafana:
    image: grafana/grafana:10.4.2
    container_name: geo-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - geo-net

networks:
  geo-net:

volumes:
  minio_data:
  clickhouse_data:
  postgres_data:
  grafana_data: